repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13 # matches the ruff version in pixi.toml
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        # Enable autofixes (equivalent to running `ruff check --fix`).
        args: ["--fix", "--exit-non-zero-on-fix"]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
