#############################################
# Churro pixi manifest
#############################################

[workspace]
channels = ["conda-forge", "main", "r", "msys2"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.*"
pip = "*"

[pypi-dependencies]
ruff = ">=0.11.13,<0.12"
pre-commit = "*"
rtree = "*"
tqdm = "*"
shapely = "*"
tenacity = "*"
diskcache = "*"
pytest = "*"
pytest-asyncio = "*"
azure-ai-documentintelligence = "==1.0.2"
pymupdf = "*"
rich = "*"
loguru = "*"
google-api-python-client = ">=2.161.0, <3"
evaluate = "*"
nltk = ">=3.9.1, <4"
rouge-score = "*"
datasets = "*"
rapidfuzz = ">=3.12.1, <4"
google-cloud-aiplatform = ">=1.85.0, <2"
anthropic = ">=0.49.0, <0.50"
pyarabic = ">=0.6.15, <0.7"
mistralai = ">=1.6.0, <2"
xmlschema = ">=4.0.1, <5"
lxml = "*"
scikit-image = ">=0.25.2, <0.26"
python-dotenv = ">=1.1.0, <2"
litellm = "==1.76.1" # stable version
docker = "*"

[feature.data.pypi-dependencies]
plotly = { version = ">=6.0.1, <7", extras = ["kaleido"] }
langcodes = ">=3.5.0, <4"
pandas = ">=2.2.3,<3"

[feature.web.dependencies]
nodejs = ">=22.12.0"

[feature.web.pypi-dependencies]
opencv-python = "*"
orjsonl = "*"
huggingface_hub = "*"
google-cloud-discoveryengine = ">=0.13.9, <0.14"
uvicorn = ">=0.34.0,<0.35"
fastapi = "*"
psycopg = ">=3.2.9, <4"
aiofiles = ">=24.1.0, <25"
qdrant-client = ">=1.14.2, <2"
async-lru = ">=2.0.5, <3"

[environments]
default = []
data = ["data"]
web = ["web"]
all = ["data", "web"]